# Generated by Django 2.2.26 on 2022-02-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyPics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(),
        ),
    ]
